name: ZombieInvasion
main: io.github.gustav9797.ZombieInvasion.ZombieInvasion
version: 0.1
depend: [OstEconomyPlugin, WorldEdit]
commands:
   createarena:
      description: Creates an arena.
      usage: /createarena name
      permission: zombieinvasion.createarena
      permission-message: You don't have zombieinvasion.createarena
   removearena:
      description: Removed an arena.
      usage: /removearena name
      permission: zombieinvasion.removearena
      permission-message: You don't have zombieinvasion.removearena
   joinarena:
      description: Joins the specified arena.
      usage: /joinarena name
      permission: zombieinvasion.joinarena
      permission-message: You don't have zombieinvasion.joinarena
   leavearena:
      description: Leaves your current arena.
      usage: /leavearena
      permission: zombieinvasion.leavearena
      permission-message: You don't have zombieinvasion.leavearena
   zombie:
      description: Spawns custom zombie.
      usage: /zombie
      permission: zombieinvasion.zombie
      permission-message: You don't have zombieinvasion.zombie
   startwave:
      description: Starts a wave.
      usage: Invalid wave!
      permission: zombieinvasion.startwave
      permission-message: You don't have zombieinvasion.startwave
   setmiddle:
      description: Sets the middle of the arena.
      usage: /setmiddle
      permission: zombieinvasion.setmiddle
      permission-message: You don't have zombieinvasion.setmiddle
   setsize:
      description: Sets the size of the arena.
      usage: Invalid size
      permission: zombieinvasion.setsize
      permission-message: You don't have zombieinvasion.setsize
   createborder:
      description: Creates a border around the arena.
      usage: /createborder
      permission: zombieinvasion.createborder
      permission-message: You don't have zombieinvasion.createborder
   removeborder:
      description: Removes the border around the arena.
      usage: /removeborder
      permission: zombieinvasion.removeborder
      permission-message: You don't have zombieinvasion.removeborder
   reset:
      description: Resets the arena.
      usage: /reset
      permission: zombieinvasion.reset
      permission-message: You don't have zombieinvasion.reset
   setlobby:
      description: Sets the lobby's location.
      usage: /setlobby
      permission: zombieinvasion.setlobby
      permission-message: You don't have zombieinvasion.setlobby