name: ZombieInvasion
main: io.github.gustav9797.ZombieInvasion.ZombieInvasion
version: 0.1
softdepend: [OstEconomyPlugin, WorldEdit]
commands:
   createarena:
      description: Creates an arena.
      permission: zombieinvasion.createarena
      permission-message: You don't have zombieinvasion.createarena
   removearena:
      description: Removed an arena.
      permission: zombieinvasion.removearena
      permission-message: You don't have zombieinvasion.removearena
   joinarena:
      description: Joins the specified arena.
      permission: zombieinvasion.joinarena
      permission-message: You don't have zombieinvasion.joinarena
   leavearena:
      description: Leaves your current arena.
      permission: zombieinvasion.leavearena
      permission-message: You don't have zombieinvasion.leavearena
   zombie:
      description: Spawns custom zombie.
      permission: zombieinvasion.zombie
      permission-message: You don't have zombieinvasion.zombie
   startwave:
      description: Starts a wave.
      permission: zombieinvasion.startwave
      permission-message: You don't have zombieinvasion.startwave
   setlocation:
      description: Sets the location of the arena.
      permission: zombieinvasion.setlocation
      permission-message: You don't have zombieinvasion.setlocation
   setsize:
      description: Sets the size of the arena.
      permission: zombieinvasion.setsize
      permission-message: You don't have zombieinvasion.setsize
   createborder:
      description: Creates a border around the arena.
      permission: zombieinvasion.createborder
      permission-message: You don't have zombieinvasion.createborder
   removeborder:
      description: Removes the border around the arena.
      permission: zombieinvasion.removeborder
      permission-message: You don't have zombieinvasion.removeborder
   reset:
      description: Resets the arena.
      permission: zombieinvasion.reset
      permission-message: You don't have zombieinvasion.reset
   setlobby:
      description: Sets the lobby's location.
      permission: zombieinvasion.setlobby
      permission-message: You don't have zombieinvasion.setlobby
   setarenaspawn:
      description: Sets the arena's spawn location.
      permission: zombieinvasion.setarenaspawn
      permission-message: You don't have zombieinvasion.setarenaspawn
   reloadzombieinvasion:
      description: Sets the arena's spawn location.
      permission: zombieinvasion.setarenaspawn
      permission-message: You don't have zombieinvasion.setarenaspawn